package mx.com.ferbo.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * CatImssCuotas generated by hbm2java
 */
@Entity
@Table(name = "cat_imss_cuotas")
@NamedQueries({
    @NamedQuery(name = "CatImssCuotas.findAll", query = "SELECT i FROM CatImssCuotas i"),
    @NamedQuery(name = "CatImssCuotas.findByActive", query = "SELECT NEW mx.com.ferbo.dto.CatImssCuotasDTO(i.idImssCuotas, i.riesgoTrabajo, i.enfMatEspCtFija, i.enfMatEspCtAd, i.enfMatGastosMed, i.enfMatDinero, i.invVida, i.retCesantiaVejezRetiro, i.retCesantiaVejezCeav, i.guarderia, i.infonavit, i.cuota, i.fechaCap, i.activo) FROM CatImssCuotas i WHERE i.activo = 1"),
    @NamedQuery(name = "CatImssCuotas.findActual", query = "SELECT NEW mx.com.ferbo.dto.CatImssCuotasDTO(i.idImssCuotas, i.riesgoTrabajo, i.enfMatEspCtFija, i.enfMatEspCtAd, i.enfMatGastosMed, i.enfMatDinero, i.invVida, i.retCesantiaVejezRetiro, i.retCesantiaVejezCeav, i.guarderia, i.infonavit, i.cuota, i.fechaCap, i.activo) FROM CatImssCuotas i WHERE i.activo = 1 AND i.fechaCap LIKE :fechaCap")})
public class CatImssCuotas implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_imss_cuotas")
    private Integer idImssCuotas;
    @NotNull
    @Column(name = "riesgo_trabajo")
    private float riesgoTrabajo;
    @NotNull
    @Column(name = "enf_mat_esp_ct_fija")
    private float enfMatEspCtFija;
    @Column(name = "enf_mat_esp_ct_ad")
    private float enfMatEspCtAd;
    @NotNull
    @Column(name = "enf_mat_gastos_med")
    private float enfMatGastosMed;
    @NotNull
    @Column(name = "enf_mat_dinero")
    private float enfMatDinero;
    @NotNull
    @Column(name = "inv_vida")
    private float invVida;
    @NotNull
    @Column(name = "ret_cesantia_vejez_retiro")
    private float retCesantiaVejezRetiro;
    @NotNull
    @Column(name = "ret_cesantia_vejez_ceav")
    private float retCesantiaVejezCeav;
    @NotNull
    @Column(name = "guarderia")
    private float guarderia;
    @NotNull
    @Column(name = "infonavit")
    private float infonavit;
    @NotNull
    @Column(name = "cuota")
    private String cuota;
    @NotNull
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_cap")
    private Date fechaCap;
    @NotNull
    @Column(name = "activo")
    private short activo;

    public CatImssCuotas() {
    }

    public CatImssCuotas(Integer idImssCuotas) {
        this.idImssCuotas = idImssCuotas;
    }

    public CatImssCuotas(Integer idImssCuotas, float riesgoTrabajo, float enfMatEspCtFija, float enfMatEspCtAd, float enfMatGastosMed, float enfMatDinero, float invVida, float retCesantiaVejezRetiro, float retCesantiaVejezCeav, float guarderia, float infonavit, String cuota, Date fechaCap, short activo) {
        this.idImssCuotas = idImssCuotas;
        this.riesgoTrabajo = riesgoTrabajo;
        this.enfMatEspCtFija = enfMatEspCtFija;
        this.enfMatEspCtAd = enfMatEspCtAd;
        this.enfMatGastosMed = enfMatGastosMed;
        this.enfMatDinero = enfMatDinero;
        this.invVida = invVida;
        this.retCesantiaVejezRetiro = retCesantiaVejezRetiro;
        this.retCesantiaVejezCeav = retCesantiaVejezCeav;
        this.guarderia = guarderia;
        this.infonavit = infonavit;
        this.cuota = cuota;
        this.fechaCap = fechaCap;
        this.activo = activo;
    }

    public Integer getIdImssCuotas() {
        return idImssCuotas;
    }

    public void setIdImssCuotas(Integer idImssCuotas) {
        this.idImssCuotas = idImssCuotas;
    }

    public float getRiesgoTrabajo() {
        return riesgoTrabajo;
    }

    public void setRiesgoTrabajo(float riesgoTrabajo) {
        this.riesgoTrabajo = riesgoTrabajo;
    }

    public float getEnfMatEspCtFija() {
        return enfMatEspCtFija;
    }

    public void setEnfMatEspCtFija(float enfMatEspCtFija) {
        this.enfMatEspCtFija = enfMatEspCtFija;
    }

    public float getEnfMatEspCtAd() {
        return enfMatEspCtAd;
    }

    public void setEnfMatEspCtAd(float enfMatEspCtAd) {
        this.enfMatEspCtAd = enfMatEspCtAd;
    }

    public float getEnfMatGastosMed() {
        return enfMatGastosMed;
    }

    public void setEnfMatGastosMed(float enfMatGastosMed) {
        this.enfMatGastosMed = enfMatGastosMed;
    }

    public float getEnfMatDinero() {
        return enfMatDinero;
    }

    public void setEnfMatDinero(float enfMatDinero) {
        this.enfMatDinero = enfMatDinero;
    }

    public float getInvVida() {
        return invVida;
    }

    public void setInvVida(float invVida) {
        this.invVida = invVida;
    }

    public float getRetCesantiaVejezRetiro() {
        return retCesantiaVejezRetiro;
    }

    public void setRetCesantiaVejezRetiro(float retCesantiaVejezRetiro) {
        this.retCesantiaVejezRetiro = retCesantiaVejezRetiro;
    }

    public float getRetCesantiaVejezCeav() {
        return retCesantiaVejezCeav;
    }

    public void setRetCesantiaVejezCeav(float retCesantiaVejezCeav) {
        this.retCesantiaVejezCeav = retCesantiaVejezCeav;
    }

    public float getGuarderia() {
        return guarderia;
    }

    public void setGuarderia(float guarderia) {
        this.guarderia = guarderia;
    }

    public float getInfonavit() {
        return infonavit;
    }

    public void setInfonavit(float infonavit) {
        this.infonavit = infonavit;
    }

    public String getCuota() {
        return cuota;
    }

    public void setCuota(String cuota) {
        this.cuota = cuota;
    }

    public Date getFechaCap() {
        return fechaCap;
    }

    public void setFechaCap(Date fechaCap) {
        this.fechaCap = fechaCap;
    }

    public short getActivo() {
        return activo;
    }

    public void setActivo(short activo) {
        this.activo = activo;
    }

    

}
